spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:30000/techlog-local?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: techlog!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update # create, create-drop, update, validate, none 중 하나 선택
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

server:
  port: 6000